### ISSUE TITLE
in the file USB2DB15.h Controller.h is in lower case

### ISSUE THREAD

**Issue by bbarthes** [Raphfriend/USB2DB15#65]
Hello,

In the file USB2DB15.h line 9, Controller.h is in lower case.
This causes a compilation error on the case-sensitive system (linux).

**Comment by Raphfriend** [comment]
When you set the "C" it compile all right?

**Comment by bbarthes** [comment]
Yes

**Comment by Raphfriend** [comment]
Fixed on [PR 69](https://github.com/Raphfriend/USB2DB15/pull/69)
